steps:
  - label: ':docker: Build Android maze runner image'
    key: "maze-runner"
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v3.3.0:
          build: android-maze-runner

  - label: ':docker: Build Android base image'
    key: "android-common"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build:
            - android-common
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
      - docker-compose#v3.3.0:
          push:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest

  - label: ':docker: Build Android base CI image (using NDK r16b)'
    key: "android-ci"
    depends_on: "android-common"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build:
            - android-ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-${BRANCH_NAME}
      - docker-compose#v3.3.0:
          push:
            - android-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-${BRANCH_NAME}

  - label: ':android: Android size reporting'
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.3.0:
          run: android-sizer

  - label: ':docker: Build Android JVM test image'
    key: "android-jvm"
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.3.0:
          build: android-jvm
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-jvm-${BRANCH_NAME}
      - docker-compose#v3.3.0:
          push:
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-jvm-${BRANCH_NAME}

  - label: ':android: Build fixture APK'
    key: "fixture-apk"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/fixture.apk
    plugins:
      - docker-compose#v3.3.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':android: Linter'
    depends_on: "android-jvm"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.3.0:
          run: android-jvm
    command: 'bash ./scripts/run-linter.sh'

  - label: ':android: JVM tests'
    depends_on: "android-jvm"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.3.0:
          run: android-jvm
    command: './gradlew test'

  - label: ':android: Android 4.4 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_4_4"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 5 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 6 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
        - "--app=/app/build/fixture.apk"
        - "--farm=bs"
        - "--device=ANDROID_6_0"
        - "--username=$BROWSER_STACK_USERNAME"
        - "--access-key=$BROWSER_STACK_ACCESS_KEY"
        - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    #
    # TODO: Remove as soon as possible - working around BrowserStack network problem
    #
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 7 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    #
    # TODO: Remove as soon as possible - working around BrowserStack network problem
    #
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 8.0 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 8.1 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 9 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 10 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 11 end-to-end tests'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"
